import { RecoveryStepName } from '@/components/onboarding/account-recovery';

export const routes = {
  HOME: '/',
  ONBOARDING: '/onboarding',
  CREATE_ACCOUNT: '/onboarding/create-account',
  BACKUP_TIPS: '/onboarding/backup-tips',
  DISPLAY_MNEMONIC: '/onboarding/display-mnemonic',
  BACKUP_MNEMONIC: '/onboarding/backup-mnemonic',
  VALIDATE_AND_CREATE: '/onboarding/validate-and-create',
  ONBOARDING_IMPORT: '/onboarding/import',
  RECOVER_ACCOUNT: '/onboarding/recover-account',
  RECOVER_ACCOUNT_SECURITY: `/onboarding/recover-account/${RecoveryStepName.SECURITY}`,
  RECOVER_ACCOUNT_DATA_COLLECTION: `/onboarding/recover-account/${RecoveryStepName.DATA_COLLECTION}`,
  RECOVER_ACCOUNT_DATA_COLLECTION_HIDDEN: `/onboarding/recover-account/${RecoveryStepName.DATA_COLLECTION}/hidden`,
  RECOVER_ACCOUNT_PASSWORD: `/onboarding/recover-account/${RecoveryStepName.PASSWORD}`,
  TOS: '/onboarding/tos',
  PK_LIST: '/pk-list',
  WALLET_LIST: '/wallet-list',
  ACCOUNT_LIST: '/account-list',
  SEND_BSV: '/send-bsv',
  RECEIVE_BSV: '/receive-bsv',
  TRANSFER_TOKEN: '/transfer-token',
  HISTORY: '/history',
  TOKENS: '/tokens',
  NFT: '/nft',
  ERROR: '/error',
  WEB_PUSH: '/web-push',
  PORTFOLIO: '/tokens',
};
